# Generated by Django 2.1.7 on 2019-03-16 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='default-slug', max_length=150)),
                ('region', models.CharField(choices=[('United States', 'United States'), ('Europe', 'Europe'), ('Korea', 'Korea')], default='United States', max_length=50)),
                ('class_name', models.CharField(choices=[('Demon Hunter', 'Demon Hunter'), ('Barbarian', 'Barbarian'), ('Witch Doctor', 'Witch Doctor'), ('Monk', 'Monk'), ('Necromancer', 'Necromancer'), ('Wizard', 'Wizard'), ('Solo', 'Solo')], default='BR', max_length=50)),
                ('game_mode', models.CharField(choices=[('Season', 'Seasonal Softcore'), ('Season HC', 'Seasonal Hardcore'), ('Nonseason', 'Nonseasonal Softcore'), ('Nonseason HC', 'Nonseasonal Hardcore')], default='SS', max_length=15)),
                ('season', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('battletag', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('rift_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('rift_time', models.DurationField()),
                ('completed_on', models.DateTimeField(verbose_name='Rift completed on')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Leaderboard')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
