# Generated by Django 2.1.7 on 2019-03-16 20:35

from django.db import migrations
from core.models import Leaderboard, Record
from core.utils import create_leaderboards, create_solo_lb


def seed_db(apps, schema_editor):
    create_leaderboards()
    create_solo_lb()
    cleanup = Record.objects.filter(rank__gt=1000).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_db)
    ]
